# Numpy

## import

In [2]:
import numpy as np

np.__version__ # numpy version

'1.25.2'

## python 라이브러리 속도 비교 예제

In [5]:
import random

rand_arr = [random.random() for i in range(100_000)] # python - list
type(rand_arr)

list

In [6]:
%%timeit
# 이 셀이 실행되는 시간
import statistics

statistics.mean(rand_arr)

63.5 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
np_rand_arr = np.array(rand_arr)
type(np_rand_arr)

numpy.ndarray

In [9]:
%%timeit
import statistics

np.mean(np_rand_arr)

44.9 µs ± 748 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## 배열 생성

In [10]:
arr = np.array([1,2,3,4,5])

arr

array([1, 2, 3, 4, 5])

In [14]:
print(arr.shape) # 차원별 데이터의 수
print(arr.ndim) # 몇 차원인지
print(arr.dtype) # array의 데이터 타입
print(arr.size) # 크기

(5,)
1
int64
5


## 생성 & 초기화

In [16]:
np.zeros((3,2)) # 0으로 채움, shape을 input으로

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones((2,3)) # 1로 채움

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((2,3),7) # 뒤에 있는 숫자로 채움

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
arr = np.array([[[1,2],[1,2]],[[1,5],[6,5]]])
np.zeros_like(arr) # arr과 같은 shape으로 채움

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [20]:
np.arange(10) # == list(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱 & 슬라이싱
<p>인덱싱 : 하나 가져오기
<p>슬라이싱 : 여러개 가져오기

In [22]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
arr[-3:]

array([5, 6, 7])

In [25]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr[1, 0] # 인덱싱

4

## Boolean 인덱싱

In [30]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([True,False,True,True,True])

arr1[arr2] # arr2의 True 자리의 데이터만 가져옴

array([1, 3, 4, 5])

In [31]:
arr1[arr1 > 2] # 조건문도 가능

array([3, 4, 5])

## Fancy 인덱싱

In [34]:
arr = np.array([1,2,3,4,5])
idx = np.array([1, 3])

arr[idx] # 1, 3 자리의 데이터를 가져옴. index로 가져오는 기능

array([2, 4])

In [35]:
arr = np.array([1,2,3,4,5])
idx = np.array([[1, 3],[0,1]])

arr[idx] # 다차원도 가능. idx를 2차원으로 설정하면 2차원으로 만들어서 가져옴

array([[2, 4],
       [1, 2]])

In [36]:
arr = np.array([1,2,3,4,5])
arr[0] = -1
arr # array의 값이 바뀌는 것이 아니라 새로운 object를 만드는 것 -> 자원 소모 많음(리스트와 차이점). ex) loop시 리스트로 진행 후 np.array로 바꿈

array([-1,  2,  3,  4,  5])

## 형태 변환

In [39]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr.reshape(-1) # 1차원 배열로 펴기, -1이 알아서 채워준다고 생각하면 됨
#arr.flatten()
#arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [41]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = arr1.reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.sum(arr2, axis=1) # axis= 축에 따라서 계산, np.mean도 동일

array([ 6, 15])

In [45]:
arr = np.array([1,2,3,4,5])
arr[np.newaxis,:] # 축 추가 기능
arr[:, np.newaxis] # 내부를 나눔

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# np.savez() : .npz 라는 형식의 파일 numpy 저장한 파일
# np.savez('test.npz', train=arr)
# arr = np.load('test.npz')
# arr['train'] 으로 불러오기